AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SME Marketing Assistant - AI API

Globals:
  Function:
    Timeout: 60
    Runtime: python3.11

Resources:
  # HTTP API
  AiApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"

  # Lambda Function
  AiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: ai_handler.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref AiApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  AiApiUrl:
    Description: "AI API Gateway endpoint URL"
    Value: !Sub "https://${AiApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
    Export:
      Name: !Sub "${AWS::StackName}-AiApiUrl"